language: php
php:
  - 5.5
  - 5.4
  - 5.3

script: phpunit -v --coverage-clover=coverage.clover

before_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - composer install --dev --prefer-source
  - sudo apt-get install -y supervisor
  - sudo cp resources/supervisord.conf /etc/

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    webhooks:
        secure: "aGUTR/3LuAgWx/VtSfQR/WCv14PUU9Zb/9Td9ybSQSgLKO+mdS4N0CmvJObtGiJTNSKUpu5Wb0LWpKEKs42oP42rO82ljTXQ2cpL/Zin/zARenNWn9zDu8j3mxzR6t6OHDGr+yD2yQYK/FMSc0vKtPOeETig1CmJziwdV849ScA="
