language: php

sudo: required

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

env:
  - SUPERVISOR_VERSION=3.0
  - SUPERVISOR_VERSION=3.1.3

matrix:
  allow_failures:
    - php: 7.0
  include:
    - php: 5.4
      env:
        - COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
        - PHPSPEC_FLAGS="-c phpspec.yml.ci"
        - COVERAGE=true

install:
  - resources/bootstrap.sh
  - phpenv config-add resources/hhvm.ini
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script:
  - vendor/bin/phpspec ${PHPSPEC_FLAGS}
  - vendor/bin/behat

after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
